version: "3"

services:
    app:
        build: .
        container_name: auth-example
        restart: always
        depends_on:
            - redis
        ports:
            - 5000:5000

    redis:
        image: redis:latest
        restart: always
        container_name: redis-auth
        ports:
            - 6380:6379
