version: "3"

services:
    app:
        build: .
        container_name: auth-example_app
        image: dewaadiperdana/auth-example:1.0.0
        restart: always
        depends_on:
            - redis
        ports:
            - 5000:5000

    redis:
        image: redis:latest
        restart: always
        container_name: auth-example_redis
        ports:
            - 6380:6379
